FROM node:11-alpine as base
## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.4.0/wait /wait
RUN chmod +x /wait
ENV NODE_ENV production
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY public public/
COPY src src/
RUN npm run build
CMD /wait && npm run server