FROM node:11-alpine as base
## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.4.0/wait /wait
RUN chmod +x /wait
ENV NODE_ENV production
WORKDIR /app
COPY front/public public/
COPY front/dist dist/
COPY back /app
RUN npm install
CMD /wait && npm run server